package com.bluecollar.notification.entity;

public enum NotificationType {
    BOOKING_CREATED,
    BOOKING_ACCEPTED,
    BOOKING_REJECTED,
    BOOKING_STARTED,
    BOOKING_COMPLETED,
    BOOKING_CANCELLED,
    REVIEW_RECEIVED,
    REVIEW_MODERATED,
    ACCOUNT_WELCOME,
    ACCOUNT_PASSWORD_CHANGED,
    ACCOUNT_DEACTIVATED,
    VERIFICATION_APPROVED,
    VERIFICATION_REJECTED,
    IDENTITY_DOC_VERIFIED,
    IDENTITY_DOC_REJECTED
}
